### ISSUE TITLE
Statement of Faith

### ISSUE THREAD

**Issue by ChrisJarka** [WycliffeAssociates/ts-android#4]
Please note that the SoF may need to be updated (as with this ISSUE for BTT Recorder)
WycliffeAssociates/translationRecorder#1185

**Comment by PurpleGuitar** [comment]
Thanks Christine!  Once we get the updated text from Ed Services we'll get it updated in the app.

**Comment by PurpleGuitar** [comment]
Statement of faith updated per Tabitha Price.
